package com.xgetsongs.shared.lyrics

/**
 * Finds the lyrics in a YouTube video description. Uploaders put them after a line that is only a heading (`[Lyrics]`,
 * `가사`, `Lyrics:`), usually between separator lines and in front of links, a copyright notice and hashtags.
 *
 * The first heading line wins; the block that follows it runs up to the first line that cannot be a lyric (a separator, a
 * link, a copyright or hashtag line, the heading of another section such as `[Rom]`) or to the end of the text. Anything
 * that does not look like a lyrics block gives null: it is better to write no lyrics than somebody's links.
 */
object LyricsExtractor {
    /** A block needs at least this many non-blank lines, else it is a stray word or a line of credit, not lyrics. */
    private const val MIN_NON_BLANK_LINES = 3

    /** Safety limit for the result (UTF-16 units); the block is cut at a line boundary. */
    private const val MAX_LENGTH = 30000

    /** The longest run of blank lines kept in the result. */
    private const val MAX_BLANK_RUN = 2

    /**
     * What is left of a heading line (only letters and digits, lowercase) when it is a lyrics heading. Exactly these and
     * nothing else: `Lyrics by X` or `Lyrics (English)` are not headings.
     */
    private val MARKERS = setOf(
        "lyrics", "lyric", "가사", "歌詞", "歌词", "lyrics가사", "가사lyrics", "lyricskorean", "lyricskor", "lyricsoriginal",
    )

    /** The characters a separator line is made of. */
    private const val SEPARATOR_CHARS = "=-_*~#.+━─═"
    private const val MIN_SEPARATOR_LENGTH = 3

    /** Link markers; a line holding one is not a lyric. */
    private val LINK_MARKERS = listOf("http://", "https://", "www.")

    /** A line starting with one of these (after trimming) is a copyright notice. */
    private val COPYRIGHT_PREFIXES = listOf("©", "ⓒ", "(c)", "copyright", "all rights reserved")

    /** A bracketed line whose letters and digits start like this is the heading of another section (romanized text, translation, credits, links). */
    private val OTHER_SECTION_PREFIXES = listOf(
        "rom", "eng", "translat", "credit", "info", "staff", "link", "sns", "follow",
        "번역", "해석", "영문", "로마", "크레딧", "정보",
    )

    /** A line (bracketed or not) whose letters and digits start like this is boilerplate that YouTube or a distributor added. */
    private val BOILERPLATE_PREFIXES = listOf("provided", "releasedon", "autogenerated")

    private val BRACKETS = listOf('[' to ']', '【' to '】', '(' to ')')

    /**
     * The lyrics found in [description] as plain text: the lines are joined with `\n`, trailing whitespace of every line
     * is gone, there is no blank line at either end and no run of more than two blank lines. Null when [description] is
     * null or blank, has no heading line, or its first lyrics block has fewer than three non-blank lines.
     */
    fun extract(description: String?): String? {
        if (description.isNullOrBlank()) return null
        val lines = normalise(description).split('\n')
        val marker = lines.indexOfFirst { key(it) in MARKERS }
        if (marker < 0) return null

        var start = marker + 1
        while (start < lines.size && (lines[start].isBlank() || isSeparator(lines[start]))) start++
        var end = start
        while (end < lines.size && !isTerminator(lines[end])) end++

        val block = limit(collapseBlankRuns(trimBlankEnds(lines.subList(start, end).map { it.trimEnd() })))
        // The cut can leave a blank line at the end, so the ends are trimmed again; the blank lines inside stay.
        val cleaned = trimBlankEnds(block)
        if (cleaned.count { it.isNotEmpty() } < MIN_NON_BLANK_LINES) return null
        return cleaned.joinToString("\n")
    }

    /** `\r\n` and `\r` become `\n`, a leading byte order mark goes, and so do the control characters other than `\n` and `\t`. */
    private fun normalise(text: String): String {
        val withoutMark = text.removePrefix("﻿")
        val unified = withoutMark.replace("\r\n", "\n").replace('\r', '\n')
        return unified.filterNot { isControl(it) && it != '\n' && it != '\t' }
    }

    private fun isControl(c: Char) = c.code < 0x20 || c.code in 0x7F..0x9F

    /** What is left of [line] when everything but letters and digits is removed, in lowercase. */
    private fun key(line: String): String = line.filter { it.isLetterOrDigit() }.lowercase()

    /** Three or more of the same separator character and nothing else (surrounding whitespace is ignored). */
    private fun isSeparator(line: String): Boolean {
        val trimmed = line.trim()
        return trimmed.length >= MIN_SEPARATOR_LENGTH && trimmed[0] in SEPARATOR_CHARS && trimmed.all { it == trimmed[0] }
    }

    /** True for a line that ends the block: it is a separator, a link, a copyright or hashtag line, boilerplate, or the heading of another section. */
    private fun isTerminator(line: String): Boolean {
        val trimmed = line.trim()
        if (isSeparator(trimmed)) return true
        if (LINK_MARKERS.any { trimmed.contains(it, ignoreCase = true) }) return true
        if (COPYRIGHT_PREFIXES.any { trimmed.startsWith(it, ignoreCase = true) }) return true
        if (trimmed.length >= 2 && trimmed[0] == '#' && !trimmed[1].isWhitespace()) return true
        val key = key(trimmed)
        if (BOILERPLATE_PREFIXES.any { key.startsWith(it) }) return true
        return isBracketed(trimmed) && (key in MARKERS || OTHER_SECTION_PREFIXES.any { key.startsWith(it) })
    }

    /** The whole line is enclosed in one pair of `[ ]`, `【 】` or `( )`. Song-structure tags such as `[Chorus]` are enclosed too, they just do not name another section. */
    private fun isBracketed(trimmed: String): Boolean =
        trimmed.length >= 2 && BRACKETS.any { (open, close) -> trimmed.first() == open && trimmed.last() == close }

    private fun trimBlankEnds(lines: List<String>): List<String> =
        lines.dropWhile { it.isEmpty() }.dropLastWhile { it.isEmpty() }

    /** Runs of three or more blank lines (the lines are already trimmed, so blank means empty) shrink to [MAX_BLANK_RUN]. */
    private fun collapseBlankRuns(lines: List<String>): List<String> {
        val result = ArrayList<String>(lines.size)
        var blankRun = 0
        for (line in lines) {
            blankRun = if (line.isEmpty()) blankRun + 1 else 0
            if (blankRun <= MAX_BLANK_RUN) result += line
        }
        return result
    }

    /** The longest run of whole lines that, joined with `\n`, stays within [MAX_LENGTH]. */
    private fun limit(lines: List<String>): List<String> {
        var length = 0
        for ((index, line) in lines.withIndex()) {
            length += if (index == 0) line.length else line.length + 1
            if (length > MAX_LENGTH) return lines.subList(0, index)
        }
        return lines
    }
}
