package com.xgetsongs.shared.lyrics

/**
 * Finds the lyrics in a YouTube video description. Uploaders put them after a line that is only a heading (`[Lyrics]`,
 * `가사`, `Lyrics:`), usually between separator lines and in front of links, a copyright notice and hashtags.
 *
 * The first heading line wins (a line of hashtags such as `#Lyrics #가사` is never a heading); the block that follows it
 * runs up to the first line that cannot be a lyric (a separator, a link, a copyright or hashtag line, the heading of
 * another section such as `[Rom]`) or to the end of the text. A line in parentheses, `(Follow me)`, is an echo line of the
 * song and never a heading. Anything that does not look like a lyrics block gives null: it is better to write no lyrics
 * than somebody's links.
 *
 * Before anything else the zero-width characters (U+200B, U+200C, U+200D, U+2060, U+FEFF) are removed and the Hangul filler
 * (U+3164, a letter that draws nothing, often typed to fake a blank line) becomes a space, so that they cannot hide a
 * heading, a separator or a blank line.
 */
object LyricsExtractor {
    /** A block needs at least this many non-blank lines, else it is a stray word or a line of credit, not lyrics. */
    private const val MIN_NON_BLANK_LINES = 3

    /** Safety limit for the result (UTF-16 units); the block is cut at a line boundary. */
    private const val MAX_LENGTH = 30000

    /** The longest run of blank lines kept in the result. */
    private const val MAX_BLANK_RUN = 2

    /**
     * What is left of a heading line (only letters and digits, lowercase) when it is a lyrics heading. Exactly these and
     * nothing else: `Lyrics by X` or `Lyrics (English)` are not headings.
     */
    private val MARKERS = setOf(
        "lyrics", "lyric", "가사", "歌詞", "歌词", "lyrics가사", "가사lyrics", "lyricskorean", "lyricskor", "lyricsoriginal",
    )

    /**
     * The characters a separator line is made of, in any mix: the ASCII `= - _ * ~ # . +`, the box-drawing lines U+2501,
     * U+2500 and U+2550, and the look-alikes uploaders type instead: the Hangul letter EU U+3161, the em dash U+2014, the
     * black rectangle U+25AC and the fullwidth equals sign U+FF1D.
     */
    private const val SEPARATOR_CHARS = "=-_*~#.+\u2501\u2500\u2550\u3161\u2014\u25AC\uFF1D"
    private const val MIN_SEPARATOR_LENGTH = 3

    /** Characters that draw nothing and are removed from the text before anything else is looked at. */
    private val ZERO_WIDTH_CHARS = setOf('\u200B', '\u200C', '\u200D', '\u2060', '\uFEFF')

    /** The Hangul filler: a letter that draws nothing. It becomes a space, so a line of it is blank and a heading with it is still a heading. */
    private const val HANGUL_FILLER = '\u3164'

    /** Link markers; a line holding one is not a lyric. */
    private val LINK_MARKERS = listOf("http://", "https://", "www.")

    /** A line starting with one of these (after trimming) is a copyright notice. */
    private val COPYRIGHT_PREFIXES = listOf("©", "ⓒ", "(c)", "copyright", "all rights reserved")

    /** A line in `[ ]` or `【 】` whose letters and digits start like this is the heading of another section (romanized text, translation, credits, links). */
    private val OTHER_SECTION_PREFIXES = listOf(
        "rom", "eng", "translat", "credit", "info", "staff", "link", "sns", "follow",
        "번역", "해석", "영문", "로마", "크레딧", "정보",
    )

    /** A line (bracketed or not) whose letters and digits start like this is boilerplate that YouTube or a distributor added. */
    private val BOILERPLATE_PREFIXES = listOf("provided", "releasedon", "autogenerated")

    /** The pairs that enclose a section heading. Parentheses are not among them: `(Follow me)` is an echo line of the song. */
    private val BRACKETS = listOf('[' to ']', '【' to '】')

    /**
     * The lyrics found in [description] as plain text: the lines are joined with `\n`, trailing whitespace of every line
     * is gone, there is no blank line at either end and no run of more than two blank lines. Null when [description] is
     * null or blank, has no heading line, or its first lyrics block has fewer than three non-blank lines.
     */
    fun extract(description: String?): String? {
        if (description.isNullOrBlank()) return null
        val lines = normalise(description).split('\n')
        val marker = lines.indexOfFirst { !isHashtagLine(it.trim()) && key(it) in MARKERS }
        if (marker < 0) return null

        var start = marker + 1
        while (start < lines.size && (lines[start].isBlank() || isSeparator(lines[start]))) start++
        var end = start
        while (end < lines.size && !isTerminator(lines[end])) end++

        return tidyLines(lines.subList(start, end))
    }

    /**
     * [text] cleaned up as lyrics, without looking for a heading or an end: the same clean-up and validity rules that
     * [extract] applies to the block it finds, for a text that already is the lyrics (the answer of a lyrics service).
     * The zero-width characters go and the Hangul filler becomes a space, line breaks become `\n`, control characters
     * other than `\n` and `\t` go, trailing whitespace of every line is gone, there is no blank line at either end and no
     * run of more than two blank lines, and the text is cut at a line boundary (never inside a surrogate pair) when it
     * would pass 30000 characters. Null when [text] is null or blank or has fewer than three non-blank lines.
     */
    fun tidy(text: String?): String? {
        if (text.isNullOrBlank()) return null
        return tidyLines(normalise(text).split('\n'))
    }

    /** The clean-up of [extract] and [tidy] for [lines] that are already normalised. */
    private fun tidyLines(lines: List<String>): String? {
        val block = limit(collapseBlankRuns(trimBlankEnds(lines.map { it.trimEnd() })))
        // The cut can leave a blank line at the end, so the ends are trimmed again; the blank lines inside stay.
        val cleaned = trimBlankEnds(block)
        if (cleaned.count { it.isNotEmpty() } < MIN_NON_BLANK_LINES) return null
        return cleaned.joinToString("\n")
    }

    /**
     * The zero-width characters (the byte order mark among them) go wherever they are, the Hangul filler becomes a space,
     * `\r\n` and `\r` become `\n`, and the control characters other than `\n` and `\t` go.
     */
    private fun normalise(text: String): String {
        val visible = text.filterNot { it in ZERO_WIDTH_CHARS }.replace(HANGUL_FILLER, ' ')
        val unified = visible.replace("\r\n", "\n").replace('\r', '\n')
        return unified.filterNot { isControl(it) && it != '\n' && it != '\t' }
    }

    private fun isControl(c: Char) = c.code < 0x20 || c.code in 0x7F..0x9F

    /** What is left of [line] when everything but letters and digits is removed, in lowercase. */
    private fun key(line: String): String = line.filter { it.isLetterOrDigit() }.lowercase()

    /** Three or more characters, all of them separator characters (any mix); surrounding whitespace is ignored. */
    private fun isSeparator(line: String): Boolean {
        val trimmed = line.trim()
        return trimmed.length >= MIN_SEPARATOR_LENGTH && trimmed.all { it in SEPARATOR_CHARS }
    }

    /** [trimmed] starts with `#` followed by something other than whitespace: a hashtag, not a heading and not a lyric. */
    private fun isHashtagLine(trimmed: String): Boolean = trimmed.length >= 2 && trimmed[0] == '#' && !trimmed[1].isWhitespace()

    /** True for a line that ends the block: it is a separator, a link, a copyright or hashtag line, boilerplate, or the heading of another section. */
    private fun isTerminator(line: String): Boolean {
        val trimmed = line.trim()
        if (isSeparator(trimmed)) return true
        if (LINK_MARKERS.any { trimmed.contains(it, ignoreCase = true) }) return true
        if (COPYRIGHT_PREFIXES.any { trimmed.startsWith(it, ignoreCase = true) }) return true
        if (isHashtagLine(trimmed)) return true
        val key = key(trimmed)
        if (BOILERPLATE_PREFIXES.any { key.startsWith(it) }) return true
        return isBracketed(trimmed) && (key in MARKERS || OTHER_SECTION_PREFIXES.any { key.startsWith(it) })
    }

    /** The whole line is enclosed in one pair of `[ ]` or `【 】`. Song-structure tags such as `[Chorus]` are enclosed too, they just do not name another section. */
    private fun isBracketed(trimmed: String): Boolean =
        trimmed.length >= 2 && BRACKETS.any { (open, close) -> trimmed.first() == open && trimmed.last() == close }

    private fun trimBlankEnds(lines: List<String>): List<String> =
        lines.dropWhile { it.isEmpty() }.dropLastWhile { it.isEmpty() }

    /** Runs of three or more blank lines (the lines are already trimmed, so blank means empty) shrink to [MAX_BLANK_RUN]. */
    private fun collapseBlankRuns(lines: List<String>): List<String> {
        val result = ArrayList<String>(lines.size)
        var blankRun = 0
        for (line in lines) {
            blankRun = if (line.isEmpty()) blankRun + 1 else 0
            if (blankRun <= MAX_BLANK_RUN) result += line
        }
        return result
    }

    /** The longest run of whole lines that, joined with `\n`, stays within [MAX_LENGTH]. */
    private fun limit(lines: List<String>): List<String> {
        var length = 0
        for ((index, line) in lines.withIndex()) {
            length += if (index == 0) line.length else line.length + 1
            if (length > MAX_LENGTH) return lines.subList(0, index)
        }
        return lines
    }
}
